In [1]:
import numpy as np

In [7]:
# Task1
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [16]:
# Task2
a1 = a.reshape(2,6)
a2 = a.reshape(3,4)
a3 = a.reshape(4,3)
a4 = a.reshape(6,2)
a5 = a.reshape(12,1)
print('a1:\n', a1)
print('a2:\n', a2)
print('a3:\n', a3)
print('a4:\n', a4)
print('a5:\n', a5)

a1:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a3:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [24]:
# Task3
a1 = a.reshape(2,-1)
a2 = a.reshape(3,-1)
a3 = a.reshape(12,-1)
a4 = a.reshape(-1,2)
a5 = a.reshape(-1,3)
print('a1:\n', a1)
print('a2:\n', a2)
print('a3:\n', a3)
print('a4:\n', a4)
print('a5:\n', a5)

a1:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a3:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
a4:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


##### Task4 
Массив из 1 столбца и 12 строк можно назвать одномерным в общем случае (если мы нарисуем его на бумаге), но не в numpy, т.к. для обращения к конкретному элементу массива необходимо задавать два параметра (номер строки и столбца), а не один (как в случае массива с 12 столбцами и 1 строкой.

In [40]:
# Task5
b = np.random.randn(3,4)
print('b:\n',b)
c = b.flatten()
print('c:\n',c)
print('Size b: ', np.size(b),'\nSize c: ',np.size(c))

b:
 [[ 0.96234626 -0.13237741  0.04441369 -2.37403032]
 [ 1.30569547 -0.67887713 -0.0442243   0.95212031]
 [ 1.33566074  0.34118614  0.02231746  0.32177391]]
c:
 [ 0.96234626 -0.13237741  0.04441369 -2.37403032  1.30569547 -0.67887713
 -0.0442243   0.95212031  1.33566074  0.34118614  0.02231746  0.32177391]
Size b:  12 
Size c:  12


In [52]:
# Task6
a = np.arange(20, 0, -2)
a
print(a, type(a))

[20 18 16 14 12 10  8  6  4  2] <class 'numpy.ndarray'>


In [53]:
# Task7
b = np.array(a).reshape(1,10)
b
print(b, type(b))

[[20 18 16 14 12 10  8  6  4  2]] <class 'numpy.ndarray'>


??? В чём разница ???

In [67]:
# Task8
a = np.zeros((2,2))
b = np.ones((3,2))
c = np.vstack((a,b))
print(c, '\n\nSize c: ',np.size(c))


[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

Size c:  10


In [80]:
# Task9
a = np.arange(0,12)
print(a)
A = a.reshape(4,3)
print(A)
At = A.T
print(At)
B = A.dot(At)
print(B,'\nSize B: ', B.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
Size B:  16


In [92]:
# Task10
np.random.seed(42)
a = np.random.random(4)
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [99]:
# Task11
# Соблюдается ли в randint равномерное распределение?
c = np.random.randint(0,16,16)
c

array([ 8,  6,  1,  3,  8, 11, 13,  1,  9,  8,  9,  4,  1,  3, 11, 14])

In [110]:
# Task12
C = c.reshape(4,4)
print(C)
D = C*10 + B
print(D)
d_det = np.linalg.det(D)
d_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(f'Определитель: ',d_det.round(),'\nРанг: ',d_rank,'\nD_inv:\n',D_inv)

[[ 8  6  1  3]
 [ 8 11 13  1]
 [ 9  8  9  4]
 [ 1  3 11 14]]
[[ 85  74  33  62]
 [ 94 160 216 132]
 [113 166 239 252]
 [ 42 152 322 442]]
Определитель:  53135600.0 
Ранг:  4 
D_inv:
 [[-0.02625885 -0.03231355  0.0641122  -0.02321908]
 [ 0.05122404  0.04548024 -0.08710356  0.02889325]
 [-0.0311392  -0.01318589  0.03972252 -0.01434142]
 [ 0.0075648  -0.00296374 -0.00507607  0.00498047]]


0.9999999999999999